### ISSUE TITLE
java.nio.BufferUnderflowException

### ISSUE THREAD

**Issue by pphan** [jblough/Android-Pdf-Viewer-Library#19]
When I open pdf, this exception is come out and keep showing loading icon. May I know what is wrong?

06-26 15:20:21.485: E/PDFVIEWER(24225): java.nio.BufferUnderflowException
06-26 15:20:21.485: E/PDFVIEWER(24225):     at java.nio.Buffer.checkGetBounds(Buffer.java:177)
06-26 15:20:21.485: E/PDFVIEWER(24225):     at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:41)
06-26 15:20:21.485: E/PDFVIEWER(24225):     at java.nio.MappedByteBufferAdapter.get(MappedByteBufferAdapter.java:144)
06-26 15:20:21.485: E/PDFVIEWER(24225):     at java.nio.ByteBuffer.get(ByteBuffer.java:384)
06-26 15:20:21.485: E/PDFVIEWER(24225):     at net.sf.andpdf.nio.NioByteBuffer.get(NioByteBuffer.java:99)
06-26 15:20:21.485: E/PDFVIEWER(24225):     at com.sun.pdfview.decode.FlateDecode.decode(FlateDecode.java:68)
06-26 15:20:21.485: E/PDFVIEWER(24225):     at com.sun.pdfview.decode.PDFDecoder.decodeStream(PDFDecoder.java:92)
06-26 15:20:21.485: E/PDFVIEWER(24225):     at com.sun.pdfview.PDFObject.decodeStream(PDFObject.java:334)
06-26 15:20:21.485: E/PDFVIEWER(24225):     at com.sun.pdfview.PDFObject.getStream(PDFObject.java:266)
06-26 15:20:21.485: E/PDFVIEWER(24225):     at com.sun.pdfview.PDFObject.getStream(PDFObject.java:260)
06-26 15:20:21.485: E/PDFVIEWER(24225):     at com.sun.pdfview.PDFFile.getContents(PDFFile.java:1642)
06-26 15:20:21.485: E/PDFVIEWER(24225):     at com.sun.pdfview.PDFFile.getPage(PDFFile.java:1577)
06-26 15:20:21.485: E/PDFVIEWER(24225):     at com.osim.corporatesales.PdfViewerActivity.showPage(PdfViewerActivity.java:780)
06-26 15:20:21.485: E/PDFVIEWER(24225):     at com.osim.corporatesales.PdfViewerActivity.access$12(PdfViewerActivity.java:770)
06-26 15:20:21.485: E/PDFVIEWER(24225):     at com.osim.corporatesales.PdfViewerActivity$3.run(PdfViewerActivity.java:260)
06-26 15:20:21.485: E/PDFVIEWER(24225):     at java.lang.Thread.run(Thread.java:856)

**Comment by pphan** [comment]
After I change at line 78 like this "public static final boolean DEFAULTKEEPCACHES = true;", it can load to pdf but resolution is very bad. I think still need to improve a lot to be prefect.
