### ISSUE TITLE
com.sun.pdfview.PDFParseException

### ISSUE THREAD

**Issue by muhammadyousufsaif** [jblough/Android-Pdf-Viewer-Library#23]
Hi,
I am using your library to show pdf in my app. I am getting this error, kindly help me to solve this problem:
11-02 03:14:15.247: W/System.err(628): com.sun.pdfview.PDFParseException: Unknown coding method:JPXDecode
11-02 03:14:15.247: W/System.err(628):  at com.sun.pdfview.decode.PDFDecoder.decodeStream(PDFDecoder.java:115)
11-02 03:14:15.257: W/System.err(628):  at com.sun.pdfview.PDFObject.decodeStream(PDFObject.java:334)
11-02 03:14:15.257: W/System.err(628):  at com.sun.pdfview.PDFObject.getStream(PDFObject.java:266)
11-02 03:14:15.257: W/System.err(628):  at com.sun.pdfview.PDFObject.getStream(PDFObject.java:260)
11-02 03:14:15.257: W/System.err(628):  at com.sun.pdfview.PDFImage.getImage(PDFImage.java:224)
11-02 03:14:15.257: W/System.err(628):  at com.sun.pdfview.PDFRenderer.drawImage(PDFRenderer.java:374)
11-02 03:14:15.257: W/System.err(628):  at com.sun.pdfview.PDFImageCmd.execute(PDFPage.java:654)
11-02 03:14:15.257: W/System.err(628):  at com.sun.pdfview.PDFRenderer.iterate(PDFRenderer.java:674)
11-02 03:14:15.266: W/System.err(628):  at com.sun.pdfview.BaseWatchable.run(BaseWatchable.java:101)
11-02 03:14:15.266: W/System.err(628):  at com.sun.pdfview.BaseWatchable.execute(BaseWatchable.java:263)
11-02 03:14:15.266: W/System.err(628):  at com.sun.pdfview.BaseWatchable.go(BaseWatchable.java:197)
11-02 03:14:15.266: W/System.err(628):  at com.sun.pdfview.PDFPage.getImage(PDFPage.java:237)
11-02 03:14:15.266: W/System.err(628):  at net.sf.andpdf.pdfviewer.PdfViewerActivity.showPage(PdfViewerActivity.java:792)
11-02 03:14:15.266: W/System.err(628):  at net.sf.andpdf.pdfviewer.PdfViewerActivity.access$12(PdfViewerActivity.java:769)
11-02 03:14:15.266: W/System.err(628):  at net.sf.andpdf.pdfviewer.PdfViewerActivity$3.run(PdfViewerActivity.java:259)
11-02 03:14:15.266: W/System.err(628):  at java.lang.Thread.run(Thread.java:1096)

Thanks in advance.
## 

Yousuf

**Comment by vikrant-shah27** [comment]
I'm also stuck in this same problem anyone have some solution about this?
Is this Library support JPXDecode format ?? @jblough
