### ISSUE TITLE
Problem showing pdf 

### ISSUE THREAD

**Issue by alo** [jblough/Android-Pdf-Viewer-Library#25]
Hi, i was trying to use your library to show a pdf in my app ant it gives me that error...

E/APV.PDFRenderer﹕ null
    java.lang.NullPointerException
            at android.graphics.Canvas.drawBitmap(Canvas.java:1195)
            at com.sun.pdfview.PDFRenderer.drawImage(PDFRenderer.java:390)
            at com.sun.pdfview.PDFImageCmd.execute(PDFPage.java:654)
            at com.sun.pdfview.PDFRenderer.iterate(PDFRenderer.java:685)
            at com.sun.pdfview.BaseWatchable.run(BaseWatchable.java:101)
            at com.sun.pdfview.BaseWatchable.execute(BaseWatchable.java:263)
            at com.sun.pdfview.BaseWatchable.go(BaseWatchable.java:197)
            at com.sun.pdfview.PDFPage.getImage(PDFPage.java:237)
            at segesa.catalogo.VisorPDF$2.doInBackground(VisorPDF.java:117)
            at segesa.catalogo.VisorPDF$2.doInBackground(VisorPDF.java:73)
            at android.os.AsyncTask$2.call(AsyncTask.java:287)
            at java.util.concurrent.FutureTask.run(FutureTask.java:234)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:856)

Its gives me the correct number of pages, but it dosent show anything. 

The pdf im trying to open is in that url 
http://www.cealsa.com/folletoiphone/folletoiphone.pdf
But im trying to open it locally, from my internal storage. 

Thanks

**Comment by ndorigatti** [comment]
My adobe reader can't open the file too... are you sure pdf file is ok?
try my version of the library at:
https://github.com/ndorigatti/Android-Pdf-Viewer-Library
